print('Anem a fer una divisió amb nombres enters')
D = int(input('Quin és el dividend de la divisió? '))
d = int(input('I el divisor? '))
print('Divisió: ', D,'/',d)
print('Quocient: ', D//d)
print('Residu: ', D%d)